### PR TITLE
updated well drill cost correlations

### PR DESCRIPTION
**Pull request by bpulluta**
Updated well drilling cost correlations to match GETEM correlations based on Sandia Report: https://www.nrel.gov/docs/fy23osti/82771.pdf

### CODE REVIEW

**Comment by softwareengineerprogrammer** [comment]
@bpulluta thanks for submitting!

First step is to get Actions (automated tests) passing, see test failure https://github.com/NREL/GEOPHIRES-X/actions/runs/8380691581/job/22950491702?pr=165#step:5:1221

**Comment by kfbeckers** [comment]
Yes, once all 16 correlations are incorporated, I would say yes that is a good idea to switch the default to Intermediate 1 - large diameter - vertical

**Comment by softwareengineerprogrammer** [comment]
Hi @bpulluta, just checking in - I'm assuming you're working on addressing the test failures and filing another revision of this PR to fix, but let me know if you would like any further guidance or info in the meantime.

**Comment by softwareengineerprogrammer** [comment]
Note: this PR, once approved/merged will probably be sufficient to resolve https://github.com/NREL/GEOPHIRES-X/issues/129 (pending evaluation of whether there are any aspects of that issue that are not addressed in this PR)

**Review by softwareengineerprogrammer — CHANGES_REQUESTED** [review]
Awaiting updated example outputs and passing Actions per https://github.com/NREL/GEOPHIRES-X/pull/165#pullrequestreview-1980559011

**Comment by bpulluta** [comment]
> ew changes to example results to ensure they are as expected for the cost correlation updates, then update this PR with updated example outputs with passing tests.

@softwareengineerprogrammer, I updated the cost correlations. Previously, I thought the previous geophires implementation was using `ideal correlations` but actually it was using `baseline correlations`. That's why we saw the cost decrease when we updated it to the new correlations. All tests are now passing correctly. 

Additionally, i added a function to `test_csv` to help track where in the csv there were differences. Nothing major but it helped me to identify the lines that needed revision.

**Comment by bpulluta** [comment]
> Awaiting updated example outputs and passing Actions per [#165 (review)](https://github.com/NREL/GEOPHIRES-X/pull/165#pullrequestreview-1980559011)

@softwareengineerprogrammer @kfbeckers , I updated the cost correlations. Previously, I thought the previous geophires implementation was using ideal correlations but actually it was using baseline correlations. That's why we saw the cost decrease when we updated it to the new correlations. As such, I fixed the implementation to call baseline correlations for the first 4 correlations. All tests are now passing correctly.

Additionally, i added a function to test_csv to help track where in the csv there were differences. Nothing major but it helped me to identify the lines that needed revision.

**Comment by softwareengineerprogrammer** [comment]
Note from offline discussion with @kfbeckers: We will file a follow-up issue to change the default correlation to intermediate 1 (no action required on @bpulluta's part)

**Review by softwareengineerprogrammer — APPROVED** [review]
Looks good!

**Pull request merged**
